src/openeo_grass_gis_driver/capabilities.py

Fixing the issues from https://github.com/Open-EO/openeo-grassgis-driver/issues/16
- GET //collections/<string:name> endpoint now only one leading slashes
- curly braces

Path variables are not enclosed in curly braces

---

src/openeo_grass_gis_driver/endpoints.py
src/openeo_grass_gis_driver/well_known.py

As demanded from v0.4.0, we need to support the /.well-known/openeo endpoint showing current available versions (https://github.com/Open-EO/openeo-api/releases/tag/0.4.0). This PR adds this endpoint.
I made it WIP because I would like to discuss if this really belongs into the code because it itself doesn't know, where it is deployed. Else, I would not know how else to support this. Any ideas? It would look like this: 
```
{
"versions": {
"0.3.1": "http://127.0.0.1:5000/api/v0.3/", 
"0.4.0": "http://127.0.0.1:5000/api/v0.4/"
}
}
```

WIP: Well known

---

src/openeo_grass_gis_driver/authentication.py
src/openeo_grass_gis_driver/test_base.py

This PR re-adds the decorator to enable authentication + fixes the tests.
With this PR, all tests pass:
```
================== 53 passed, 1 warning in 109.52s (0:01:49) ===================
```

re-enable auth fix tests

---

src/openeo_grass_gis_driver/actinia_processing/actinia_interface.py
src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/main.py
src/openeo_grass_gis_driver/processes.py
src/openeo_grass_gis_driver/register_actinia_processes.py
src/openeo_grass_gis_driver/register_processes.py

To exploit more functionality of actinia and therefore of GRASS GIS, all modules (grass-modules and actinia-modules) are registered on startup with this PR. This way they appear as processes under `/processes` endpoint. For now, only "id", "description" and "categories" are shown for external processes (depending on actinia-gdi endpoint).
Snippet of response containing default openeo process "variance", grass-module "r.quantile" and actinia-module "slope_aspect":
```
{
"deprecated": false,
"description": "Computes the sample variance of an array of numbers by calculating the square of the standard deviation (see ``sd()``).",
"experimental": false,
"id": "variance",
"links": [],
"parameters": [
{
"deprecated": false,
"description": "An array of numbers.",
"experimental": false,
"name": …
```

register actinia modules on startup

---

docker/Dockerfile
src/openeo_grass_gis_driver/actinia_processing/config.py

This PR fixes the CMD value from the Dockerfile. Additionally it changes a config value. A ticket for easier configuration was already opened (https://github.com/Open-EO/openeo-grassgis-driver/issues/76), so rebuild of application won't be necessary when config changes in the future.

Update docker cmd and config

---

src/openeo_grass_gis_driver/register_actinia_processes.py

With this PR, all information from r.slope.aspect are included in process list, created during startup. When this approach is more feasable than collecting this information later, a suitable way needs to be implemented to add all modules on startup alreay (more likely needs to be implemented in actinia-module-plugin).

Add more infos to r.slope.aspect

---

src/openeo_grass_gis_driver/actinia_processing/actinia_interface.py
src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/processes_process_id.py
src/openeo_grass_gis_driver/register_actinia_processes.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v10.py

For openeo process names, "only letters (a-z), numbers and underscores" are allowed, see 
https://api.openeo.org/#section/Processes/Defining-Processes
Therefore dots in actinia module names need to be translated to underscores, e.g. r.slope.aspect to r_slope_aspect.
The original actinia module names are still available in the id of the entries of ACTINIA_PROCESS_DESCRIPTION_DICT 
and needed to translate openeo process names to actinia module names.

openeo GRASS driver: actinia modules

---

src/openeo_grass_gis_driver/actinia_processing/aggregate_spatial_process.py
src/openeo_grass_gis_driver/actinia_processing/filter_spatial_process.py
src/openeo_grass_gis_driver/actinia_processing/mask_polygon_process.py
src/openeo_grass_gis_driver/jobs_job_id.py
src/openeo_grass_gis_driver/models/service_schemas.py
tests/test_process_graph_validation.py

openeo GRASS driver: continue linting

---

src/openeo_grass_gis_driver/app.py
src/openeo_grass_gis_driver/endpoints.py
src/openeo_grass_gis_driver/test_base.py
src/openeo_grass_gis_driver/well_known.py
tests/test_actinia_interface.py
tests/test_capabilities.py
tests/test_collections.py
tests/test_jobs.py
tests/test_process_definitions.py
tests/test_process_graph.py
tests/test_process_graph_generation.py
tests/test_process_graph_validation.py
tests/test_processes.py
tests/test_result.py
tests/test_udf.py
tests/test_well_known.py

To make deployment independent of nginx, the openeo-grassgis-driver is - with this PR - able to add the API version prefix itself. As this is an api breaking change when used without nginx, a major release will be necessary afterwards.

Url prefix

---

src/openeo_grass_gis_driver/collections.py

With this PR, the response to `/collections` is cached directly in the openeo-grassgis-driver without the need for nginx or similar to handle the cache.
The cache will be filled on application startup and can be cleared with `/collections?cache=false`
Related to https://github.com/Open-EO/openeo-grassgis-driver/pull/85

Add cache for collections

---

src/openeo_grass_gis_driver/capabilities.py
src/openeo_grass_gis_driver/endpoints.py

This PR replaces the static links in the capabilities response and finds out during current request, what the actual host is.
Tested locally with `http://127.0.0.1:5000`, `http://0.0.0.0:5000` and `http://localhost:5000` it works.

Make links dynamic

---

config/sample.ini
src/openeo_grass_gis_driver/actinia_processing/config.py

Fixes #76
The config.py now sets some default values. They can be overwritten by anything which is in the configured config folder, ending with `*.ini`. The config folder is either located at `config` or can be set with environment variable `DEFAULT_CONFIG_PATH`.
The taken config values are written out into a file. If more config files exist, it can be usefull for debugging.

Make config configurable

---

src/openeo_grass_gis_driver/capabilities.py

This PR shows the current backend version, depending on latest release. Currently for my local dev setup I get:
```
{
"api_version": "1.0.1",
"backend_version": "2.0.2.post0.dev1+gf5c22a5",
"description": "GRASS GIS Driver",
```
For deployed releases, this will look more nice and clean, e.g. only `2.0.2` . Before, `"backend_version": "0.2.0"` was hard coded.

Add live backend version

---

src/openeo_grass_gis_driver/actinia_processing/config.py

When deploying with kubernetes, the config is mounted as a configmap. This way, it is mounted read only and on startup the following error appears:
```
OSError: [Errno 30] Read-only file system: '/etc/default/openeo-grassgis-driver/openeo-grassgis-driver.cfg'
```
This PR comments according code out. It was only used for debugging reasons. Maybe a better solution can be found.

Avoid os error

---

src/openeo_grass_gis_driver/actinia_processing/config.py

Most values can be configured via separate config file. For the locations this seemed possible, but apparent array `LOCATIONS = ["nc_spm_08", "utm32n", "latlong_wgs84"]` will be simply interpreted as string by configparser. This leads to following error when requesting the collections endpoint:
`An internal error occurred while catching mapset from location [!"`
This PR keeps the appearence of an array in the config file and reads it in as an array instead of string.

Parse locations from config as array

---

.flake8
src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/endpoints.py

This PR fixes all lint errors except `501 - line too long` which it now ignores per file/folder. Current status :
```
2     E127 continuation line over-indented for visual indent
409   E501 line too long (120 > 79 characters)
1     F401 'openeo_grass_gis_driver.capabilities.CAPABILITIES' imported but unused
1     F811 redefinition of unused 'CAPABILITIES' from line 8
```
status with this PR:
```
0
```

Make lint check green

---

.github/workflows/docker.yml

Dockerhub no longer runs autobuilds itself. To have current docker images, github actions are now used to build and push docker images.
This PR adds a github action, which
- on push to branch `master`, build and push image to dockerhub with tag ref - e.g. `sha-7cc2976`
- on release, build and push image to dockerhub with tag containing semver release version - e.g. `1.2.3`
- updates tag `latest` where appropriate

Add docker build + push action

---

src/openeo_grass_gis_driver/actinia_processing/apply_process.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v10.py
tests/test_process_graph_validation.py

fix parsing of the process graph inside the apply process definition

openeo grass driver: fix apply process

---

.github/workflows/docker.yml
src/openeo_grass_gis_driver/collections.py
src/openeo_grass_gis_driver/register_actinia_processes.py

This PR
* prevents duplicate workflow run for release. Currently, GHA for docker builds is triggered for releases when they are created and published. This makes sense, when pre-releases are created but not in our case. This PR reduces the trigger to the creation of a release.
* enhances log output

tiny enhancements

---

src/openeo_grass_gis_driver/collection_information.py

use metadata from actinia instead of guessing

openeo grass driver

---

src/openeo_grass_gis_driver/collection_information.py

The spatial extents of a raster data cube must be given with a bbox of the form [xmin, ymin, xmax, ymax], irrespective of the axis order of the used CRS. The default CRS is EPSG:4326 where by definition y is the first axis and x is the second axis, resulting in a bbox of [ymin, xmin, ymax, xmax]. This PR makes reported bboxes conform to openeo specification, irrespective of the CRS axis order specification.
This PR assumes that GDAL 3+ is used, but does not test for it.

openeo-grass-driver: fix bbox axis order

---

.flake8
requirements.txt
src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/register_actinia_processes.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v10.py

Some GRASS `t.rast.*` modules have two required output options, `output` for the strds and `basename` for the new raster maps. With this PR, `basename` will be set automatically in the openeo GRASS driver for selected GRASS modules, fulfilling the openeo requirement of only one output per process.

openeo GRASS driver: improve GRASS module wrapping

---

src/openeo_grass_gis_driver/actinia_processing/actinia_interface.py
src/openeo_grass_gis_driver/collection_information.py
src/openeo_grass_gis_driver/collections.py
src/openeo_grass_gis_driver/models/collection_schemas.py

With the implementation of [actinia-stac-plugin](https://github.com/mundialis/actinia-stac-plugin) and this PR, it is now possible to also request STAC collections registered in actinia. They will be integrated in the collections list and can be requested by id.
For this feature to work, actinia needs to be installed with the actinia-stac-plugin. If it is not installed, the STAC collections are simply not included in the `/collections` response (like before).
"Normal" STRDS:
STAC collection:
There are some differences in attributes but I decided to not use the `CollectionInformation`. See more detailed explanation why in comment in `src/openeo_grass_gis_driver/collection_information.py `

Integrate actinia stac collections

---

src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/collections.py
src/openeo_grass_gis_driver/register_actinia_processes.py
src/openeo_grass_gis_driver/utils/logging.py

This PR introduces a logger. By default it prints logs to STDOUT in JSON format. It is not configurable yet but if this is needed it can be done in a separate PR.
One example log is integrated in `collections.py`. The line `log.warning("Couldn't get STAC collections from actinia")` will look like the following in the STDOUT log output:
```
{"time": "2021-11-19T16:50:00.811279Z", "level": "WARNING", "component": "openeo-grass-gis-driver", "module": "collections", "message": "Couldn't get STAC collections from actinia", "pathname": "/src/openeo_grass_gis_driver/src/openeo_grass_gis_driver/collections.py", "lineno": 97, "processName": "MainProcess", "threadName": "Thread-10"}
```
Depending on deployment, simple `print` statements are not visible in STDOUT/collected for docker logs. These …

Introduce logger

---

.vscode/launch.json
.vscode/tasks.json
config/sample.ini

This PR enhances the local dev setup when developing together with a local actinia-core instance.
As actinia-core also has a dev setup with vscode, this PR adds the option to use the same docker network as actinia to be able to connect to it. In this case, the network must exist before which is the case when debugger with vscode for actinia-core was started before.
Related to https://github.com/mundialis/actinia_core/pull/288

Enhance dev setup

---

src/openeo_grass_gis_driver/actinia_processing/filter_temporal_process.py
src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py
src/openeo_grass_gis_driver/collection_information.py
src/openeo_grass_gis_driver/jobs_job_id.py
src/openeo_grass_gis_driver/jobs_job_id_results.py

* temporal filters are left-closed intervals
* report extents for spatial dimensions in `cube:dimensions`
* do not report previous status, but check current status for endpoint `jobs/{job_id}`
* delete actinia resources when cancelling or deleting a job

openeo GRASS driver: fix temporal filter, fix extents

---

src/openeo_grass_gis_driver/capabilities.py
src/openeo_grass_gis_driver/well_known.py

Support access paths like `https://www.host.com/openeo-backend/`

support nginx with access path

---

src/openeo_grass_gis_driver/jobs_job_id.py
src/openeo_grass_gis_driver/jobs_job_id_results.py

If the status of an actinia resource is 400, the job status must be updated accordingly.

update job status in case of actinia error

---

.flake8
src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py
src/openeo_grass_gis_driver/collection_information.py
src/openeo_grass_gis_driver/collections.py
src/openeo_grass_gis_driver/local_collections.py

This PR adds support for local external collections where raster data are located in a local folder structure. These collections are described with json files following openEO syntax for collections. The json files must be located in `LOCAL_COLLECTIONS`, by default `$HOME/.openeo_local_collections`. Contents of this folder are read with the endpoints `/collections` and `collections/{collection_id}` and also when a collection is loaded with `load_collection`.

add support for local external collections

---

RELEASE.md
src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py

Handling of the new collection type was missing in one place

fix pc entry creation for load_collection
