Open-EO/openeo-grassgis-driver

_sources/index.rst.txt
index.html

Update github pages

---

src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/test_base.py
tests/test_capabilities.py
tests/test_collections.py
tests/test_jobs.py
tests/test_preview.py
tests/test_process_graph.py
tests/test_process_graph_validation.py
tests/test_processes.py
tests/test_udf.py

This PR adds authentication to tests

Add auth to tests

---

src/openeo_grass_gis_driver/actinia_processing/actinia_interface.py

The tests are not successful anymore due to new basic auth and change of permissions / locations in actinia-core deployment at actinia.mundialis.de. This PR tries to fix them again
- added auth and user in interface init for tests

WIP: fix tests

---

src/openeo_grass_gis_driver/collections.py
src/openeo_grass_gis_driver/jobs.py
src/openeo_grass_gis_driver/processes.py

removes auth from certain endpoints, related to #18

---

src/openeo_grass_gis_driver/actinia_processing/__init__.py
src/openeo_grass_gis_driver/actinia_processing/apply_mask_process.py
src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/actinia_processing/filter_bbox_process.py
src/openeo_grass_gis_driver/actinia_processing/mask_invalid_values_process.py
src/openeo_grass_gis_driver/actinia_processing/multilayer_mask_process.py
src/openeo_grass_gis_driver/actinia_processing/ndvi_process.py
src/openeo_grass_gis_driver/actinia_processing/percentile_time_process.py
src/openeo_grass_gis_driver/actinia_processing/reduce_time_process.py
src/openeo_grass_gis_driver/actinia_processing/scale_minmax_process.py
src/openeo_grass_gis_driver/models/error_schemas.py

Openeo grass driver usecase 1

---

src/openeo_grass_gis_driver/actinia_processing/__init__.py
src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/actinia_processing/mask_invalid_values_process.py
src/openeo_grass_gis_driver/actinia_processing/mask_process.py
src/openeo_grass_gis_driver/actinia_processing/resample_process.py

Should be merged soon.
More processes will be added later on.

Openeo grass driver usecases

---

requirements.txt
src/openeo_grass_gis_driver/app.py

Also updates the Werkzeug version.
@neteler @mundialis-dev Please review.

Fix usage of the x-forwarded-* headers

---

.gitignore
src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/app.py
src/openeo_grass_gis_driver/authentication.py
src/openeo_grass_gis_driver/capabilities.py
src/openeo_grass_gis_driver/endpoints.py
src/openeo_grass_gis_driver/jobs.py
src/openeo_grass_gis_driver/jobs_job_id.py
src/openeo_grass_gis_driver/jobs_job_id_results.py
src/openeo_grass_gis_driver/process_graph_validation.py
src/openeo_grass_gis_driver/process_graphs.py
src/openeo_grass_gis_driver/result.py
src/openeo_grass_gis_driver/test_base.py
src/openeo_grass_gis_driver/token_db.py

Adds a rudimentary bearer based authentication mechanism.
@mundialis-dev Please review.

Add rudimentary bearer authentication mechanism

---

src/openeo_grass_gis_driver/actinia_processing/__init__.py
src/openeo_grass_gis_driver/actinia_processing/evi_process.py
src/openeo_grass_gis_driver/actinia_processing/normalized_difference_process.py
src/openeo_grass_gis_driver/actinia_processing/resample_process.py

+evi
+normalized difference
process to detect start and end of a season is still missing

openeo_grass_gis_driver

---

src/openeo_grass_gis_driver/actinia_processing/__init__.py
src/openeo_grass_gis_driver/actinia_processing/reduce_process.py

Adds the `reduce` process. Currently includes only a skeleton process that converts its input to a formula string. The actual process must still be chosen and created properly.
For now, only `+-*/` and simple functions without arguments are supported.
@metzm Please review & merge as needed.

WIP: Add reduce process

---

src/openeo_grass_gis_driver/actinia_processing/filter_bbox_process.py
src/openeo_grass_gis_driver/actinia_processing/reduce_process.py

different procedures for dimension types "temporal" and "bands"

WIP reduce process

---

src/openeo_grass_gis_driver/actinia_processing/filter_bbox_process.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v03.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v04.py
tests/test_process_definitions.py

adjust for new GRASS addon module g.region.bbox

filter_bbox

---

src/openeo_grass_gis_driver/actinia_processing/__init__.py
src/openeo_grass_gis_driver/actinia_processing/filter_bbox_process.py
src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py
src/openeo_grass_gis_driver/result.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v04.py
tests/test_process_definitions.py

update the process and affected tests

load_collections

---

docs/index.rst

update of apidocs to API 0.4 (yet incomplete)

---

docker/Dockerfile
src/openeo_grass_gis_driver/actinia_processing/aggregate_spatial_process.py
src/openeo_grass_gis_driver/actinia_processing/filter_bands_process.py
src/openeo_grass_gis_driver/actinia_processing/filter_bbox_process.py
src/openeo_grass_gis_driver/actinia_processing/merge_cubes_process.py
src/openeo_grass_gis_driver/actinia_processing/trim_cube_process.py
src/openeo_grass_gis_driver/authentication.py
src/openeo_grass_gis_driver/capabilities.py
src/openeo_grass_gis_driver/endpoints.py
src/openeo_grass_gis_driver/files.py
src/openeo_grass_gis_driver/jobs.py
src/openeo_grass_gis_driver/jobs_job_id_estimate.py
src/openeo_grass_gis_driver/jobs_job_id_logs.py
src/openeo_grass_gis_driver/jobs_job_id_results.py
src/openeo_grass_gis_driver/models/collection_schemas.py
src/openeo_grass_gis_driver/models/error_schemas.py
src/openeo_grass_gis_driver/models/job_schemas.py
src/openeo_grass_gis_driver/models/process_graph_schemas.py
src/openeo_grass_gis_driver/processes.py
src/openeo_grass_gis_driver/well_known.py
tests/test_capabilities.py

Openeo API 1.0.0

---

src/openeo_grass_gis_driver/actinia_processing/__init__.py
src/openeo_grass_gis_driver/actinia_processing/reduce_dimension_process.py
src/openeo_grass_gis_driver/actinia_processing/rename_labels_process.py

openeo grass driver

---

src/openeo_grass_gis_driver/app.py

Renames CORS_SUPPORT_CREDENTIALS to CORS_SUPPORTS_CREDENTIALS (https://flask-cors.readthedocs.io/en/latest/configuration.html)

fix cors param

---

docs/index.rst
src/openeo_grass_gis_driver/models/process_schemas.py

not sure how much this matters in `src/openeo_grass_gis_driver/models/process_schemas.py`...

fixed depricated -> deprecated

---

src/openeo_grass_gis_driver/udf.py

Fixes #18 for `/udf_runtimes` .

remove auth from udf_runtimes

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/actinia_processing/mask_process.py
src/openeo_grass_gis_driver/processes_process_id.py
src/openeo_grass_gis_driver/test_base.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v10.py
tests/test_actinia_interface.py
tests/test_jobs.py
tests/test_process_graph_validation.py

add generic translation of actinia processes from openeo pg to actinia pg
waiting for https://github.com/mundialis/actinia-gdi/pull/44

openeo GRASS driver: support actinia processes

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/processes_process_id.py
src/openeo_grass_gis_driver/register_actinia_processes.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v10.py

use standard type: object, subtype: raster-cube for actinia module raster/strds input/output

adjust schema type and subtype of actinia processes

---

src/openeo_grass_gis_driver/actinia_processing/config.py

This PR allows to set the default config path via environment variable.

Allow to define config path via env

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/processes_process_id.py
src/openeo_grass_gis_driver/register_actinia_processes.py

* one output per openeo process
* translate grass modules to openeo process names and back

openeo grass driver: actinia processes

---

src/openeo_grass_gis_driver/register_actinia_processes.py

to see which actinia instance is configured and collections are requested from on statup

Enhance log

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/processes_process_id.py
src/openeo_grass_gis_driver/register_actinia_processes.py
src/openeo_grass_gis_driver/utils/process_graph_examples_v10.py

remember single output for pseudo processes

openeo grass driver: fix pseudo processes for actinia modules

---

src/openeo_grass_gis_driver/collection_information.py

Reported Sentinel 2 band names were incomplete/wrong. This PR fixes this.

open-grass-driver: fix the fix for collection_information

---

src/openeo_grass_gis_driver/actinia_processing/mask_process.py

openeo-grass-driver: fix mask process

---

src/openeo_grass_gis_driver/actinia_processing/reduce_dimension_process.py
src/openeo_grass_gis_driver/actinia_processing/trim_cube_process.py

reduce_dimension with dimension=time should now produce a GRASS strds instead of a GRASS raster

openeo-grass-driver: fix output of reduce_dimension

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/actinia_processing/ndvi_process.py

* update ndvi process
* expand list of basename modules

openeo GRASS driver: update ndvi process

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
docker/dev/Dockerfile
setup.cfg
src/openeo_grass_gis_driver/actinia_processing/actinia_interface.py
src/openeo_grass_gis_driver/actinia_processing/config.py
src/openeo_grass_gis_driver/collections.py

this PR:
- adds a local dev setup with vscode
- enables the openeo-grassgis-driver to be connected to an actinia with version `v2` and makes this configurable
- adds missing dependencies
- prevents error when stac collections are empty

Local dev setup with vscode & some tiny fixes

---

src/openeo_grass_gis_driver/collections.py

This PR fixes the check for collected STAC collections in the `/collections` endpoint.

Fix stac collection check

---

src/openeo_grass_gis_driver/collection_information.py

GRASS 80: band_names -> semantic_labels

openeo GRASS driver: adjust for semantic labels

---

src/openeo_grass_gis_driver/actinia_processing/mask_polygon_process.py
src/openeo_grass_gis_driver/actinia_processing/mask_process.py

With this PR, any band names present in the input are transferred to the output

use t.rast.mask for the mask process

---

src/openeo_grass_gis_driver/actinia_processing/apply_process.py
src/openeo_grass_gis_driver/actinia_processing/mask_process.py
src/openeo_grass_gis_driver/actinia_processing/ndvi_process.py
src/openeo_grass_gis_driver/actinia_processing/rename_labels_process.py
src/openeo_grass_gis_driver/actinia_processing/udf_reduce_time.py

S2 timescan

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py
src/openeo_grass_gis_driver/result.py

Stac collection loader

---

src/openeo_grass_gis_driver/actinia_processing/base.py
src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py

Trying to eliminate `instance` which makes only sense within actinia, but not in the openeo backend.

improve stac support

---

requirements.txt

Avoid `ImportError: cannot import name 'escape' from 'jinja2'`, use a newer version of Flask and Flask-RESTful

use newer version of Flask

---

src/openeo_grass_gis_driver/actinia_processing/mask_polygon_process.py

* fix bugs in the implementation of mask_polygon
* black formatting

fix mask_polygon

---

.github/workflows/codeql-analysis.yml
.github/workflows/docker.yml
.github/workflows/flake8.yml

This PR updates the GHA as well as the ubuntu image in `flake8.yml`.

CI: update GitHub actions
